import Main from "../components/Main.jsx";
import AboutMe from '../components/Aboutme.jsx';
import Skills from "../components/Skills.jsx";
import MyProjects from '../components/MyProjects.jsx'; 
import Contact from "../components/Contact.jsx";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Keamogetswe | Portfolio</title>
        <meta name="description" content="Generated by next app" />
        <link rel="logo" href="/favicon.io" />
      </Head>

      
      <Main/>
      <AboutMe/>
      <Skills/>
      <MyProjects/>
      <Contact/>
    </div>
  );
}
